title: "Paschal Uzoegwu"
logo: "/assets/img/pp.jpeg"
theme: "jekyll-theme-minimal"

# Social Links
social_links:
  twitter: "https://twitter.com/sparkysparo"
  github: "https://github.com/sparkysparo"
  linkedin: "https://www.linkedin.com/in/uzoegwu-paschal/"



